### PR TITLE
refactored for es6 age

### LINKED ISSUE #5: No error handling in Connect() method
If the AVR isn't reachable, the Onkyo.prototype.Connect methods should catch the exception from "net.js" and provide a defined callback.

### PR DESCRIPTION
**Pull request by jupe**
## Status
**READY**

## Description
including several fixes and improvements including circleci which runs  eslint validation and basic tests and generate coverage report..

Fixes #5 and covers #7 and #8 

## Todo
 - [x] Test (coverage is not yet very high)

### CODE REVIEW

**Comment by VonOx** [comment]
Will this PR be merged ?

**Comment by jupe** [comment]
Unfortunately I’vent had time to implement tests and verify changes really works..

**Comment by VonOx** [comment]
Ok i understand

**Comment by jupe** [comment]
@VonOx any chance to try this out ?

**Comment by VonOx** [comment]
Yes I will test asap

**Comment by VonOx** [comment]
@jupe both control and discover sample works:

```
~/onkyo.js/sample$ node discover.js 
Detected: TX-NR646#0
Detected: TX-NR646#0 192.168.1.51:60128
```

But got error with control.js
```javascript
~/onkyo.js/sample$ node control.js 
connected
Unhandled rejection Error: Unknown data
    at Onkyo._parseMsg (/home/vonox/onkyo.js/lib/Onkyo.js:149:27)
    at Promise.try (/home/vonox/onkyo.js/lib/Onkyo.js:155:12)
    at tryCatcher (/home/vonox/onkyo.js/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vonox/onkyo.js/node_modules/bluebird/js/release/method.js:39:29)
    at Onkyo._parseClientData (/home/vonox/onkyo.js/lib/Onkyo.js:153:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

Unhandled rejection Error: Unknown data
    at Onkyo._parseMsg (/home/vonox/onkyo.js/lib/Onkyo.js:149:27)
    at Promise.try (/home/vonox/onkyo.js/lib/Onkyo.js:155:12)
    at tryCatcher (/home/vonox/onkyo.js/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vonox/onkyo.js/node_modules/bluebird/js/release/method.js:39:29)
    at Onkyo._parseClientData (/home/vonox/onkyo.js/lib/Onkyo.js:153:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

Unhandled rejection Error: Unknown data
    at Onkyo._parseMsg (/home/vonox/onkyo.js/lib/Onkyo.js:149:27)
    at Promise.try (/home/vonox/onkyo.js/lib/Onkyo.js:155:12)
    at tryCatcher (/home/vonox/onkyo.js/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vonox/onkyo.js/node_modules/bluebird/js/release/method.js:39:29)
    at Onkyo._parseClientData (/home/vonox/onkyo.js/lib/Onkyo.js:153:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

Unhandled rejection Error: Unknown data
    at Onkyo._parseMsg (/home/vonox/onkyo.js/lib/Onkyo.js:149:27)
    at Promise.try (/home/vonox/onkyo.js/lib/Onkyo.js:155:12)
    at tryCatcher (/home/vonox/onkyo.js/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vonox/onkyo.js/node_modules/bluebird/js/release/method.js:39:29)
    at Onkyo._parseClientData (/home/vonox/onkyo.js/lib/Onkyo.js:153:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

Unhandled rejection Error: Unknown data
    at Onkyo._parseMsg (/home/vonox/onkyo.js/lib/Onkyo.js:149:27)
    at Promise.try (/home/vonox/onkyo.js/lib/Onkyo.js:155:12)
    at tryCatcher (/home/vonox/onkyo.js/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vonox/onkyo.js/node_modules/bluebird/js/release/method.js:39:29)
    at Onkyo._parseClientData (/home/vonox/onkyo.js/lib/Onkyo.js:153:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by jupe** [comment]
Thanks for testing 👍 . Needs small more tuning to handle unknown messages properly - I’ll do it soon. I would like to see then what was those unrecognized messages in your case..

**Comment by VonOx** [comment]
There is a way to help you in that case ?

**Comment by jupe** [comment]
Yes, There is "dummy feature" that generates `unknown_msgs.txt` file when unrecognised
 data is received from amplifier - see [`sample/control.js`](https://github.com/jupe/onkyo.js/pull/3/files#diff-bcdbce491e3070603341797bf2d93ccdR4) - just run it again. Please attach logs/file here so I can check what I can do for them..

**Comment by jupe** [comment]
@VonOx I did several changes - I'm getting happy with changes and I would be thankful if you could re-trying before I merging this.. :)

**Comment by VonOx** [comment]
Thank you @jupe , finally you find some time ;) to work in

Just a speed test ,i got a timeout 
```
~/onkyo.js/sample$ node control.js 
connected
TimeoutError: operation timed out
    at afterTimeout (/home/vonox/onkyo.js/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/home/vonox/onkyo.js/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

and unknown_msgs
```
RX: unknown event: Error: Unknown data: NLSC-P
RX: unknown event: Error: Unrecognised key: LMDN/A
```

discover.js is ok

**Comment by jupe** [comment]
Big thank for testing :) most probably your receiver does not support NLS command and that why it fails - anyway it still should not timeouts - instead reject properly. Have to look at why it timeouts - it would help if you could run with debug prints: `DEBUG=* node control.js` to see what happens behind.. I’ll add more command supports, including LMD..

**Comment by jupe** [comment]
I found at least one clear reason for timeouts - UDP packets was not handler enough robust way. But:
```
onkyo.js TX-msg: !1AMT00 +1ms
  onkyo.js TX: ISCP%00%00%00%10%00%00%00%08%01%00%00%00!1AMT00%0D +0ms
  onkyo.js TimeoutError: operation timed out
  onkyo.js     at afterTimeout (/home/vonox/onkyo.js/node_modules/bluebird/js/release/timers.js:46:19)
  onkyo.js     at Timeout.timeoutTimeout [as _onTimeout] (/home/vonox/onkyo.js/node_modules/bluebird/js/release/timers.js:76:13)
  onkyo.js     at ontimeout (timers.js:498:11)
  onkyo.js     at tryOnTimeout (timers.js:323:5)
  onkyo.js     at Timer.listOnTimeout (timers.js:290:5) +4s
```
it looks that your receiver did not respond anything during 4 seconds.. Maybe lib sends it too quickly or something else is wrong.. hmm.. need more investigation.

I also added those unrecognised events - could you try one more time ? :)

**Comment by VonOx** [comment]
cli tool works fine (except fot thx / not available for my receiver ), maybe you can implement discover, this will prevent cli.js modification.

Timeout is weird issue, for sure specific to my network

Good Job anyway :+1:

**Comment by jupe** [comment]
> maybe you can implement discover, this will prevent cli.js modification

true - will do it 👍 

> Pulled latest commit, all is working now ( no timeout )

Great ! :)

**Comment by jupe** [comment]
@VonOx I just [publish v0.4.0 release](https://github.com/jupe/onkyo.js/releases/tag/v0.4.0) to npm. Please raise new ticket if you find any more issues/ideas what we could change/add.

**Pull request merged**
